apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-10
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-10
  project: default
  source:
    repoURL: https://github.com/tranzzik/argocd-katas.git  # Update this URL if the helm chart is in a different repo
    targetRevision: HEAD
    path: quotes-flask/helm/quotes-flask
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true